version: '3'

services:
  mysql-mba-fiap:
    image: mysql:8.0
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'fiap-mba'
      MYSQL_DATABASE: 'bancofiap'
    ports: 
      - '3306:3306'
    volumes:
      - $PWD/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  myadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: mysql-mba-fiap
    ports:
      - '8880:80'
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

