server:
  port: 8081

spring:
  datasource:
    # url: jdbc:mysql://0.0.0.0:3306/bancofiap?createDatabaseIfNotExist=true
    url: jdbc:h2:file:../db/sigint;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: fiap-mba
    # driver-class-nam: com.mysql.cj.jdbc.Driver
    # url: jdbc:h2:./db/DatabaseBatch;DB_CLOSE_ON_EXIT=FALSE
    # username: fiap
    # password: fiap
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:schema.sql

file: 
  chunk: 5
  resource: clientes.txt
