spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bancofiap
    username: root
    password: root
    driver-class-nam: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:schema.sql

file: 
  chunk: 5
  resource: clientes.txt
