spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/bancofiap
    username: root
    password: fiap-mba
    driver-class-nam: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:schema.sql

file: 
  chunk: 5
  resource: clientes.txt
