server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./db/sigint;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console