server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:../db/sigint;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://0.0.0.0:3306/bancofiap?createDatabaseIfNotExist=true
    username: root
    password: fiap-mba
    # driver-class-nam: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console