server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bancofiap
    username: root
    password: 12106153
    driver-class-nam: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console