server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bancofiap
    username: root
    password: fiap-mba 
    driver-class-nam: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
